color:
  when: always
  theme: custom
icons:
  when: auto
  theme: fancy
  separator: " "
layout: oneline
size: short
permission: rwx
hyperlink: never
no-symlink: false
symlink-arrow: '>'
blocks:
  - permission
  - size
  - date
  - name
