default_color_bg=0x{{ theme.background | strip }}
default_color_fg=blue
dialog_attr=
dialog_attr_selected=reverse
dialog_color_bg=0x{{ theme.background | strip }}
dialog_color_fg=0x{{ theme.foreground_secondary | strip }}
dialog_shaded_color_bg=
dialog_shaded_color_fg=0x{{ theme.foreground_secondary | strip }}
entry_attr=
entry_color_bg=0x{{ theme.background | strip }}
entry_color_fg=0x{{ theme.foreground_secondary | strip }}
help_attr=reverse
help_color_bg=0x{{ theme.background | strip }}
help_color_fg=0x{{ theme.foreground_secondary | strip }}
history_name_attr=bold
history_name_attr_selected=reverse
history_name_recv_color_bg=
history_name_recv_color_fg=0x{{ theme.blue | strip }}
history_name_recv_group_color_bg=
history_name_recv_group_color_fg=0x{{ theme.cyan | strip }}
history_name_sent_color_bg=
history_name_sent_color_fg=0x{{ theme.bright_blue | strip }}
history_text_attachment_color_bg=
history_text_attachment_color_fg=0x{{ theme.muted | strip }}
history_text_attr=
history_text_attr_selected=reverse
history_text_quoted_color_bg=
history_text_quoted_color_fg=0x{{ theme.muted | strip }}
history_text_reaction_color_bg=
history_text_reaction_color_fg=0x{{ theme.bright_yellow | strip }}
history_text_recv_color_bg=
history_text_recv_color_fg=0x{{ theme.foreground_secondary | strip }}
history_text_recv_group_color_bg=
history_text_recv_group_color_fg=0x{{ theme.foreground_secondary | strip }}
history_text_sent_color_bg=
history_text_sent_color_fg=0x{{ theme.foreground_bright | strip }}
list_attr=
list_attr_selected=reverse
list_color_bg=0x{{ theme.background | strip }}
list_color_fg=0x{{ theme.list_highlight | strip }}
listborder_attr=
listborder_color_bg=0x{{ theme.background | strip }}
listborder_color_fg=0x{{ theme.muted | strip }}
status_attr=bold
status_color_bg=0x{{ theme.background_status | strip }}
status_color_fg=0x{{ theme.foreground_secondary | strip }}
top_attr=reverse
top_color_bg=0x{{ theme.foreground_secondary | strip }}
top_color_fg=0x{{ theme.background | strip }}
