from typing import Any

COMMAND_DATA: int
COMMAND_BREAKPOINTS: int
COMMAND_FILES: int
COMMAND_OBSCURE: int
COMMAND_RUNNING: int
COMMAND_STACK: int
COMMAND_STATUS: int
COMMAND_SUPPORT: int
COMMAND_USER: int

TYPE_CODE_PTR: int
TYPE_CODE_ARRAY: int
TYPE_CODE_STRUCT: int
TYPE_CODE_UNION: int
TYPE_CODE_ENUM: int
TYPE_CODE_INT: int
TYPE_CODE_FLT: int
TYPE_CODE_VOID: int
TYPE_CODE_TYPEDEF: int
TYPE_CODE_FUNC: int
TYPE_CODE_REF: int
TYPE_CODE_CHAR: int
TYPE_CODE_BOOL: int
TYPE_CODE_STRING: int

pretty_printers: list[Any]

class error(Exception): ...

class Field:
    name: str
    type: "Type"
    bitpos: int
    artificial: bool

class Type:
    code: int
    name: str | None
    sizeof: int
    tag: str | None
    def fields(self) -> list[Field]: ...
    def target(self) -> "Type": ...
    def strip_typedefs(self) -> "Type": ...
    def pointer(self) -> "Type": ...
    def array(self, n1: int, n2: int | None = ...) -> "Type": ...
    def template_argument(self, n: int) -> "Type | Value": ...

class Value:
    def __init__(self, val: Any, type: "Type | None" = ...) -> None: ...
    address: "Value"
    type: Type
    dynamic_type: Type
    is_optimized_out: bool
    is_lazy: bool
    def dereference(self) -> "Value": ...
    def referenced_value(self) -> "Value": ...
    def cast(self, type: Type) -> "Value": ...
    def string(self, encoding: str = ..., errors: str = ..., length: int = ...) -> str: ...
    def fetch_lazy(self) -> None: ...
    def __getitem__(self, key: str | int) -> "Value": ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __add__(self, other: Any) -> "Value": ...
    def __sub__(self, other: Any) -> "Value": ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Command:
    def __init__(
        self,
        name: str,
        command_class: int,
        completer_class: int = ...,
        prefix: bool = ...,
    ) -> None: ...
    def invoke(self, argument: str, from_tty: bool) -> None: ...
    def dont_repeat(self) -> None: ...

class Function:
    def __init__(self, name: str) -> None: ...
    def invoke(self, *args: Any) -> Any: ...

class Frame:
    def name(self) -> str | None: ...
    def function(self) -> Any: ...
    def pc(self) -> int: ...
    def read_var(self, name: str) -> Value: ...
    def select(self) -> None: ...
    def older(self) -> "Frame | None": ...
    def newer(self) -> "Frame | None": ...

class Inferior:
    num: int
    pid: int
    def threads(self) -> tuple[Any, ...]: ...
    def read_memory(self, address: int, length: int) -> memoryview: ...

class Objfile:
    filename: str
    pretty_printers: list[Any]

def parse_and_eval(expr: str) -> Value: ...
def execute(command: str, from_tty: bool = ..., to_string: bool = ...) -> str | None: ...
def lookup_type(name: str, block: Any = ...) -> Type: ...
def lookup_symbol(name: str, block: Any = ..., domain: int = ...) -> tuple[Any, bool]: ...
def lookup_global_symbol(name: str, domain: int = ...) -> Any: ...
def selected_frame() -> Frame: ...
def selected_inferior() -> Inferior: ...
def inferiors() -> tuple[Inferior, ...]: ...
def current_objfile() -> Objfile | None: ...
def objfiles() -> list[Objfile]: ...
def write(string: str, stream: int = ...) -> None: ...
def flush() -> None: ...
