IgnorePath '/var/*'
IgnorePath '/swapfile'
IgnorePath '/boot/vmlinuz-linux'
IgnorePath '/boot/initramfs-linux.img'
IgnorePath '/boot/initramfs-linux-fallback.img'
IgnorePath '/boot/amd-ucode.img'
IgnorePath '/boot/EFI/BOOT/BOOTX64.EFI'
IgnorePath '/boot/EFI/systemd/systemd-bootx64.efi'
IgnorePath '/boot/EFI/Linux'
IgnorePath '/boot/EFI/Linux/*'

# Caches regenerated by package post-install hooks
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/icons/*/icon-theme.cache'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled'
IgnorePath '/usr/lib/gconv/gconv-modules.cache'
IgnorePath '/usr/lib/gdk-pixbuf-2.0/*/loaders.cache'
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/lib/gtk-3.0/3.0.0/immodules.cache'
IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/modules/*'
IgnorePath '/usr/lib/ghc-*/lib/package.conf.d/*'
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/lib/libvsscript.so'

# CA trust store (regenerated by update-ca-trust hook)
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/ssl/certs/*'

# Fontconfig symlinks (managed by font package hooks)
IgnorePath '/etc/fonts/conf.d/*'

# systemd unit enablement: most .wants/ symlinks are created automatically by
# `systemctl preset` (package install hooks) or by Alias= directives in unit
# files. User-chosen enablement is declared explicitly in 20-services.sh.
IgnorePath '/etc/systemd/system/*.target.wants/*'
IgnorePath '/etc/systemd/system/*.service.wants/*'
IgnorePath '/etc/systemd/system/dbus-org.*'
IgnorePath '/etc/systemd/system/autovt@.service'
IgnorePath '/etc/systemd/system/display-manager.service'
IgnorePath '/etc/systemd/user/*'

# Runtime/system state
IgnorePath '/etc/.updated'
IgnorePath '/etc/adjtime'
IgnorePath '/boot/loader/random-seed'
IgnorePath '/.bash_history'
IgnorePath '/lost+found/*'
IgnorePath '/etc/fstab.backup'

# Pacman version-conflict markers — merge or delete on the system, never in config
IgnorePath '*.pacnew'
IgnorePath '*.pacsave'

# shadow-utils backup files (/etc/passwd-, group-, shadow-, gshadow-, subuid-, subgid-)
IgnorePath '/etc/*-'

# Machine-unique IDs — must be regenerated on every install
IgnorePath '/etc/machine-id'
IgnorePath '/etc/nvme/hostid'
IgnorePath '/etc/nvme/hostnqn'

# SSH host keys — must be per-machine, regenerated on first boot
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/etc/ssh/moduli'

# pacman GPG keyring — rebuild with `pacman-key --init && pacman-key --populate archlinux`
IgnorePath '/etc/pacman.d/gnupg'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/pacman.d/gnupg/*/*'

# Regenerated caches not yet covered above
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/texmf/ls-R'
IgnorePath '/etc/texmf/web2c/updmap.cfg'
IgnorePath '/usr/lib32/gconv/gconv-modules.cache'
IgnorePath '/usr/share/texmf-dist/ls-R'

# DNS resolver state (managed by NetworkManager / tailscale)
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/resolv.pre-tailscale-backup.conf'
IgnorePath '/etc/NetworkManager/system-connections/Clio.nmconnection'
IgnorePath '/etc/NetworkManager/system-connections/Garcia.nmconnection'
IgnorePath '/etc/NetworkManager/system-connections/Wired\ connection\ 1.nmconnection'

# Package-managed symlinks / empty stubs
IgnorePath '/etc/os-release'
IgnorePath '/etc/sddm.conf'

# Empty/orphan runtime dirs
IgnorePath '/etc/userdb'
IgnorePath '/etc/cni/net.d'
IgnorePath '/etc/cni/net.d/*'
IgnorePath '/opt/containerd'
IgnorePath '/opt/containerd/*'

# Ghost: package was removed, file deletion claim no longer relevant
IgnorePath '/usr/include/sp.h'

# Foreign packages we don't want tracked (debug syms, discontinued, redundant).
# Leaves them installed but invisible to aconfmgr — uninstall separately if desired.
IgnorePackage --foreign neofetch
IgnorePackage --foreign paru-git-debug
IgnorePackage --foreign yay-debug
IgnorePackage --foreign slippi-online-appimage

IgnoreFile /etc/group
IgnoreFile /etc/gshadow
IgnoreFile /etc/passwd
IgnoreFile /etc/shadow
IgnoreFile /etc/subgid
IgnoreFile /etc/subuid
IgnorePath '/etc/mullvad-vpn/*'

IgnorePath '/usr/share/applications'
IgnorePath '/usr/share/applications/*'

# Configured by archinstall on a fresh install — no need to track in this repo.
IgnorePath '/etc/fstab'
IgnorePath '/etc/hostname'
IgnorePath '/etc/locale.conf'
IgnorePath '/etc/locale.gen'
IgnorePath '/etc/localtime'
IgnorePath '/etc/pacman.conf'
IgnorePath '/etc/pacman.d/mirrorlist'
IgnorePath '/etc/vconsole.conf'
IgnorePath '/etc/mkinitcpio.conf'
IgnorePath '/etc/sudoers.d/*'


IgnorePath /etc/udev/rules.d
IgnorePath /etc/valkey
IgnorePath /etc/valkey/sentinel.conf
IgnorePath /etc/valkey/sentinel.conf
IgnorePath /usr/bin/groupmems
IgnorePath /usr/bin/groupmems
IgnorePath /usr/bin/mullvad-exclude
IgnorePath /usr/lib/utempter/utempter
IgnorePath /usr/lib/utempter/utempter
IgnorePath /usr/share/applications
IgnorePath /etc/systemd/system/sockets.target.wants/avahi-daemon.socket
IgnorePath /etc/systemd/system/sockets.target.wants
IgnorePath /etc/systemd/system/multi-user.target.wants/tailscaled.service
IgnorePath /etc/systemd/system/multi-user.target.wants/sshd.service
IgnorePath /etc/systemd/system/multi-user.target.wants/prometheus-nvidia-gpu-exporter.service
IgnorePath /etc/systemd/system/multi-user.target.wants/prometheus-node-exporter.service
IgnorePath /etc/systemd/system/multi-user.target.wants/mullvad-daemon.service
IgnorePath /etc/systemd/system/multi-user.target.wants/libvirtd.service
IgnorePath /etc/systemd/system/multi-user.target.wants/keyd.service
IgnorePath /etc/systemd/system/multi-user.target.wants/docker.service
IgnorePath /etc/systemd/system/multi-user.target.wants/avahi-daemon.service
IgnorePath /etc/systemd/system/multi-user.target.wants/NetworkManager.service
IgnorePath /etc/systemd/system/multi-user.target.wants
IgnorePath /etc/systemd/system/default.target.wants/code-server@spader.service
IgnorePath /etc/systemd/system/default.target.wants
IgnorePath /etc/systemd/system/bluetooth.target.wants/bluetooth.service
IgnorePath /etc/systemd/system/bluetooth.target.wants

